### ISSUE TITLE
Consonant clusters not properly broifying

### ISSUE THREAD

**Issue by smaye81** [cgeorg/broify#1]
There are certain combinations of consonant clusters that aren't broifying correctly:

phone -> pbrone
plop -> pbrop
gloss -> gbross
slop -> sbrop
strong -> sbrong
chosen -> cbrosen
scrounge -> sbrounge
chrome -> cbrome
snow -> sbrow

**Comment by cgeorg** [comment]
Also:
glock -> gbrock
phone -> pbrone
chrome -> cbrome
github.io -> githubroo
snowball -> sbrowbroll
blow -> bbrow
throw -> tbrow

**Comment by smaye81** [comment]
github.io is in a separate issue since it seems unrelated to consonant clusters.  But if you want to make this one a catch-all, we can.  Some of yours are duplicated in mine.

**Comment by cgeorg** [comment]
This is fixed in release 2.5.0
