### ISSUE TITLE
Suggestion for bro approach with words ending in b + long vowel sound

### ISSUE THREAD

**Issue by smaye81** [cgeorg/broify#2]
Should we still broify the ending syllable if it is a b followed by a long vowel sound?

For example:

`bro kobe` -> `brobro`.
`bro oglebay` -> `broglebroy`

I feel like these should be `brobe` and `broglebay`.  Just spitballing though.

**Comment by cgeorg** [comment]
But shouldn't

`placebo -> placebro`

I think for words ending in o, the replacement needs to remain.  Let me think about other `b[aeiuy]+\b` examples to make sure I can't find a good reason not to.  I suppose a philosophy for the package should also be set - is it better to have bro'd and overbro'd, or never to have bro'd at all?  Should we be more tolerant of over-broification or under-broification?  My initial thoughts are that the funniest instances I've seen have been from surprise over-broification.

**Comment by smaye81** [comment]
I agree.  +1 for over-broification

On Tue, Jul 7, 2015 at 11:14 PM, Chris Marasti-Georg <
notifications@github.com> wrote:

> But shouldn't
> 
> placebo -> placebro
> 
> I think for words ending in o, the replacement needs to remain. Let me
> think about other b[aeiuy]+\b examples to make sure I can't find a good
> reason not to. I suppose a philosophy for the package should also be set -
> is it better to have bro'd and overbro'd, or never to have bro'd at all?
> Should we be more tolerant of over-broification or under-broification? My
> initial thoughts are that the funniest instances I've seen have been from
> surprise over-broification.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cgeorg/broify/issues/2#issuecomment-119408595.

## 

Steve Ayers

Senior Technical Consultant | Summa
[m]  412.708.2828
steve.ayers@summa-tech.com dfm@summa-tech.com

http://www.summa-tech.com
